services:
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql+mysqlconnector://root:1234@database/test1

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test1
    ports:
      - "3307:3306"
