name: Docker Image CI

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push가 발생할 때 작동
  pull_request:
    branches: [ "main" ]  # main 브랜치에 pull request가 열릴 때 작동

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets에서 설정한 Docker Hub 사용자명
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secrets에서 설정한 Docker Hub 비밀번호
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 현재 레포지토리 체크아웃

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Docker Buildx 설정

      - name: Docker login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push Docker image
        env:
          IMAGE_TAG: dept/docker_test  # Docker Hub 레포지토리/이미지 이름 설정
        run: |
          docker-compose -f path/to/your/docker-compose.yml build
          docker-compose -f path/to/your/docker-compose.yml push
